### ISSUE TITLE
E-tickets/arrivals

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#406]
- [x] We need a printable arrivals voucher - for entry and badge collection (needs to say that), with a separate page for parking tickets. The admission voucher should identify the user, not the ticket (#352).
- [x] We have barcode readers, which prefer reading barcodes to qrcodes. However, we also need a human fallback, and for parking attendants to be able to spot check tickets on arrival (with timeout).
- [x] If the tickets aren't scanned, we need them to check ID (#426).
- [x] It should be possible to flag a ticket as "please contact X from Orga" (#238).
- [x] Day tickets should show up differently (in a different colour or something) (#427).

**Comment by Jonty** [comment]
I suggest printing both QR and regular barcodes, just in case the light, the reader, or the phase of the moon make one or the other easier to read with whatever devices we're using - will has more readers that are different again. Can't hurt to cover all bases!

**Comment by marksteward** [comment]
Yep. Plan is to remove the human-readable string and add a barcode instead. There'll only be one set per ticket page.

**Comment by Jonty** [comment]
Why would we remove the human readable string? Or do you mean we'll have a barcode with a built-in string of digits under it?

**Comment by marksteward** [comment]
Cuz it's not really needed - the fallback is name + ID.

**Comment by Jonty** [comment]
:dunce_face:

**Comment by marksteward** [comment]
Closing as everything's done or in a separate ticket.
